# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  database: piliderevo.ru
  pool: 2
  username: piliderevoru
  password: rXn4fzVsYTn7VHyr
test:
  adapter: mysql2
  encoding: utf8
  database: piliderevo.ru
  pool: 2
  username: piliderevoru
  password: rXn4fzVsYTn7VHyr
production:
  adapter: mysql2
  encoding: utf8
  database: piliderevo.ru
  pool: 2
  username: piliderevoru
  password: rXn4fzVsYTn7VHyr
  secret_key_base: <%= ENV["SECRET_KEY_MASTERDELOVRU"] %>